#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoMecanica
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LoginDB")]
	public partial class ProgrammingClassDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTable_OSev(Table_OSev instance);
    partial void UpdateTable_OSev(Table_OSev instance);
    partial void DeleteTable_OSev(Table_OSev instance);
    #endregion
		
		public ProgrammingClassDataContext() : 
				base(global::AutoMecanica.Properties.Settings.Default.LoginDBConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public ProgrammingClassDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProgrammingClassDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProgrammingClassDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ProgrammingClassDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Table_OSev> Table_OSev
		{
			get
			{
				return this.GetTable<Table_OSev>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Table_OSev")]
	public partial class Table_OSev : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _ClienteName;
		
		private System.Nullable<System.DateTime> _DataEntrada;
		
		private System.Nullable<System.TimeSpan> _TempoServico;
		
		private string _TipoServiço;
		
		private string _FuncionarioName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnClienteNameChanging(string value);
    partial void OnClienteNameChanged();
    partial void OnDataEntradaChanging(System.Nullable<System.DateTime> value);
    partial void OnDataEntradaChanged();
    partial void OnTempoServicoChanging(System.Nullable<System.TimeSpan> value);
    partial void OnTempoServicoChanged();
    partial void OnTipoServiçoChanging(string value);
    partial void OnTipoServiçoChanged();
    partial void OnFuncionarioNameChanging(string value);
    partial void OnFuncionarioNameChanged();
    #endregion
		
		public Table_OSev()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClienteName", DbType="NChar(50)")]
		public string ClienteName
		{
			get
			{
				return this._ClienteName;
			}
			set
			{
				if ((this._ClienteName != value))
				{
					this.OnClienteNameChanging(value);
					this.SendPropertyChanging();
					this._ClienteName = value;
					this.SendPropertyChanged("ClienteName");
					this.OnClienteNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataEntrada", DbType="DateTime2")]
		public System.Nullable<System.DateTime> DataEntrada
		{
			get
			{
				return this._DataEntrada;
			}
			set
			{
				if ((this._DataEntrada != value))
				{
					this.OnDataEntradaChanging(value);
					this.SendPropertyChanging();
					this._DataEntrada = value;
					this.SendPropertyChanged("DataEntrada");
					this.OnDataEntradaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TempoServico", DbType="Time")]
		public System.Nullable<System.TimeSpan> TempoServico
		{
			get
			{
				return this._TempoServico;
			}
			set
			{
				if ((this._TempoServico != value))
				{
					this.OnTempoServicoChanging(value);
					this.SendPropertyChanging();
					this._TempoServico = value;
					this.SendPropertyChanged("TempoServico");
					this.OnTempoServicoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoServiço", DbType="NVarChar(50)")]
		public string TipoServiço
		{
			get
			{
				return this._TipoServiço;
			}
			set
			{
				if ((this._TipoServiço != value))
				{
					this.OnTipoServiçoChanging(value);
					this.SendPropertyChanging();
					this._TipoServiço = value;
					this.SendPropertyChanged("TipoServiço");
					this.OnTipoServiçoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FuncionarioName", DbType="NVarChar(50)")]
		public string FuncionarioName
		{
			get
			{
				return this._FuncionarioName;
			}
			set
			{
				if ((this._FuncionarioName != value))
				{
					this.OnFuncionarioNameChanging(value);
					this.SendPropertyChanging();
					this._FuncionarioName = value;
					this.SendPropertyChanged("FuncionarioName");
					this.OnFuncionarioNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
